version: '3'

services:
  nginx:
    depends_on:
      - db
    image: daocloud.io/piresdev/nginx-php-fpm:master
    #image: php:7.1-fpm-alpine
    container_name: nginx
    volumes:
      - ./configs/nginx.conf.d:/etc/nginx/conf.d
      - ./html:/var/www/html
      - ./configs/supervisor.conf.d:/etc/supervisor/conf.d
      - ./configs/crontab.d:/var/spool/cron/crontabs
    environment:
      VIRTUAL_HOST: boilerplate.pires.cn
    network_mode: bridge
    ports:
      - 80:80
      - 443:443
    restart: always
  db:
    image: daocloud.io/library/mysql:5.7.4
    container_name: mysql
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    network_mode: bridge
