version: '2'

services:
  nginx:
    depends_on:
      - db
    image: daocloud.io/piresdev/nginx-php-fpm:master
    #image: php:7.1-fpm-alpine
    container_name: nginx
    volumes:
      - ./configs/nginx.conf.d:/etc/nginx/conf.d
      - ./html:/var/www/html
      - ./configs/supervisor.conf.d:/etc/supervisor/conf.d
      - ./configs/crontab.d:/var/spool/cron/crontabs
      - ./configs/certs:/etc/letsencrypt
    environment:
      VIRTUAL_HOST: boilerplate.pires.cn
    network_mode: host
    ports:
      - 80:80
      - 443:443
    restart: always
  db:
      #image: daocloud.io/library/mysql:5.7.4
    image: mysql:5.7.21
    container_name: mysql
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: marathon52
    network_mode: host
  redis:
    image: redis
    container_name: redis
    network_mode: host
    ports:
      - 6379:6379
    restart: always
